apiVersion: v1
kind: LimitRange
metadata:
  name: pod-resource-limits
  namespace: default # Change this to the namespace where you want to apply the limits
spec:
  limits:
  - type: Pod
    max:
      cpu: "700m"
      ephemeral-storage: "2Gi"
    min:
      cpu: "250m"
      ephemeral-storage: "1Gi"
  - type: Container
    default:
      cpu: "250m"
      ephemeral-storage: "1Gi"
    defaultRequest:
      cpu: "250m"
      ephemeral-storage: "1Gi"
    max:
      cpu: "700m"
      ephemeral-storage: "2Gi"
    min:
      cpu: "250m"
      ephemeral-storage: "1Gi"
